apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- all.yaml
patches:
- path: patch.yaml
  target:
    kind: Deployment
    name: pet-clinic-deployment
    namespace: petclinic
    
