apiVersion: apps/v1
kind: Deployment
metadata:
  name: patch-for-application
spec:
  template:
    spec:
      initContainers:
        - name: java-agent-initializer
          image: digmaai/java-agent-initializer:latest
          volumeMounts:
            - name: shared
              mountPath: /shared-vol
      volumes:
        - name: shared
          emptyDir: {}
