services:
  digma-compound:
    image: java-agent-initializer:latest
    build: .
    volumes:
    - "java_agent_data:/shared-vol/"
    environment:
      OTEL_AGENT_VERSION: "latest"
      DIG_AGENT_VERSION: "latest"
      DIG_EXT_VERSION: "latest"

volumes:
  java_agent_data: