apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic-deployment
  labels:
    app: pet-clinic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-clinic-app
  template:
    metadata:
      labels:
        app: pet-clinic-app
    spec:
      containers:
        - name: pet-clinic
          image: springio/petclinic:latest
          env:
            - name: SOME_EXISTING_ENV
              value: some_value
          volumeMounts: []
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  selector:
    app: pet-clinic-app
  ports:
    - port: 8080
      protocol: TCP
